import sys,io,re,os
sys.stdout=io.TextIOWrapper(sys.stdout.buffer,encoding='utf-8',errors='replace')
p=r'd:\project\code\maths\黎曼猜想\riemann_thesis_en_final.md'
t=open(p,'r',encoding='utf-8',errors='replace').read()
print('size:',len(t),'lines:',t.count('\n')+1)
hs=re.findall(r'^#{1,4}\s+.+$',t,flags=re.M)
print('HEADINGS (%d):'%len(hs))
for h in hs[:60]: print(h)
if len(hs)>60: print('...%d more'%(len(hs)-60))
print()
print('inline $:',t.count('$'))
print('display $$:',t.count('$$'))
print('\\(',t.count(r'\('))
print('\\[',t.count(r'\['))
print('``` fences:',t.count('```'))
print('--- TABLE ROWS SAMPLE (first 20) ---')
rows=[l for l in t.split('\n') if l.strip().startswith('|')]
for l in rows[:20]: print(l[:160])
print('--- TABLE ROWS total:',len(rows))
print()
print('--- FIRST 40 LINES ---')
for i,l in enumerate(t.split('\n')[:40]): print(f'{i+1:3d}: {l[:160]}')
print()
lines=t.split('\n')
print('--- LINES 400-450 ---')
for i in range(400,min(450,len(lines))): print(f'{i+1:3d}: {lines[i][:200]}')
print()
print('--- LINES 1000-1050 ---')
for i in range(1000,min(1050,len(lines))): print(f'{i+1:3d}: {lines[i][:200]}')
